### ISSUE TITLE
A little doubt...

### ISSUE THREAD

**Issue by fb82** [ducha-aiki/wisv2019-competition#1]
Why  ? :-|

https://github.com/ducha-aiki/wisv2019-competition/blob/279b15ce569036b293f421bb4989e932e7ebcd33/wiswUtils.py#L80

**Comment by ducha-aiki** [comment]
We take corrs one by one and fill the distance with INF or other large number. 
So finally, we will have 1xn sub-matrix with non-inf.   SNN ratio is
(dist_to_1st_closest / dist_to_2nd_closest)
In one row(column) we will have one dist_to_2nd_closest!=inf. So inf will dominate and will be meaningless. Anyway, the last correspondence has the worst quality by definition, so we assign the worst possible quality by hand.

E.g. from real output. last -1 is quite consistent with others 

84.000,1051.000,-1.004
305.000,1326.000,-1.003
1286.000,1243.000,-1.003
605.000,1726.000,-1.003
851.000,924.000,-1.002
2186.000,1709.000,-1.002
1343.000,676.000,-1.001
1757.000,814.000,-1.000

**Comment by fb82** [comment]
Ok!
